### ISSUE TITLE
Add communities section

### ISSUE THREAD

**Issue by swaminathanvetri** [ChendrayanV/GABBLR#5]
Add communities section below the sponsors section and add the below communities

- BDotNet [Meetup](https://www.meetup.com/BDotNetUG/) | [Facebook Group](https://www.facebook.com/groups/BDotNet)
- Microsoft Azure Bengaluru [Meetup](https://www.meetup.com/Microsoft-Azure-Bangalore/)
- Bangalore IT Pro @ChendrayanV  - pls provide the meetup and other social links here
- Jas' community

**Comment by TarunReddy-Penthara** [comment]
Can you provide Meetup and social media links for the User group organized by Chandrayan?
